search_terms:

  produce:
    breadth:
      - apples
      - bananas
      - oranges
      - tomatoes
      - berries
    drilldown:
      - gala apples
      - granny smith apples
      - roma tomatoes
      - cherry tomatoes
      - strawberries
      - blueberries
      - raspberries
      - blackberries

  dairy:
    breadth:
      - milk
      - cheese
      - eggs
      - butter
      - yogurt
    drilldown:
      - whole milk
      - 2% milk
      - fat free milk
      - almond milk
      - oat milk
      - cheddar cheese
      - mozzarella cheese
      - greek yogurt

  meat_seafood:
    breadth:
      - chicken
      - beef
      - turkey
      - fish
      - shrimp
    drilldown:
      - chicken breast
      - chicken thighs
      - ground chicken
      - ground beef
      - beef steak
      - ground turkey
      - raw shrimp
      - salmon fillet

  bakery:
    breadth:
      - bread
      - rolls
      - bagels
      - muffins
      - buns
    drilldown:
      - whole wheat bread
      - white bread
      - hamburger buns
      - hot dog buns
      - english muffins
      - croissants
      - dinner rolls
      - sandwich bread

  beverages:
    breadth:
      - soda
      - juice
      - water
      - coffee
      - tea
    drilldown:
      - sparkling water
      - orange juice
      - apple juice
      - cold brew coffee
      - ground coffee
      - green tea
      - black tea
      - energy drink

  snacks:
    breadth:
      - chips
      - crackers
      - cookies
      - popcorn
    drilldown:
      - potato chips
      - tortilla chips
      - sandwich cookies
      - snack crackers
      - microwave popcorn
      - pretzels
  
  candy:
    breadth:
      - candy
      - chocolate candy
      - gummy candy

  frozen:
    breadth:
      - frozen meals
      - frozen vegetables
      - frozen fruit
      - ice cream
      - frozen pizza
    drilldown:
      - frozen broccoli
      - frozen mixed vegetables
      - frozen berries
      - vanilla ice cream
      - chocolate ice cream
      - frozen pancakes
      - frozen chicken nuggets
      - breakfast burritos
      - breakfast sandwiches
      - frozen waffles

  canned_packaged:
    breadth:
      - canned soup
      - canned beans
      - canned vegetables
      - canned tuna
      - packaged meals
    drilldown:
      - chicken noodle soup
      - black beans
      - canned corn
      - canned green beans
      - canned chili
      - canned tomatoes
      - canned salmon
      - instant

  breakfast:
    breadth:
      - cereal
      - oatmeal
      - pancake
      - waffle
      - breakfast bars
    drilldown:
      - cold cereal
      - granola cereal
      - instant oatmeal
      - pancake mix
      - waffle mix

  sauces:
    breadth:
      - pasta sauce
    drilldown:
      - alfredo sauce
      - marinara sauce

  condiment_sauces:
    breadth:
      - ketchup
      - mustard
      - mayonnaise
      - yellow mustard
    drilldown:
      - dijon mustard
      - italian dressing
      - tomato ketchup
      - ranch dressing
      - salad dressing
      - soy sauce


  personal_care:
    breadth:
      - shampoo
      - soap
      - toothpaste
      - deodorant
      - lotion
    drilldown:
      - body wash
      - hand soap
      - whitening toothpaste
      - antiperspirant deodorant
      - face lotion
      - sunscreen
      - shaving cream
      - razors

  cleaning_products:
    breadth:
      - laundry detergent
      - dish soap
      - cleaning spray
      - sponges
      - trash bags
    drilldown:
      - liquid laundry detergent
      - dishwasher detergent
      - disinfecting wipes
      - glass cleaner
      - all purpose cleaner
      - scrub sponges
      - paper towels
      - floor cleaner
      - light bulbs
      - paper cups

  baby:
    breadth:
      - baby food
      - baby formula
      - diapers
      - baby wipes
      - baby lotion
    drilldown:
      - infant formula
      - toddler snacks
      - sensitive baby wipes
      - baby shampoo
      - baby soap
      - baby sunscreen
      - baby snacks
      - electrolyte drinks

  pet_care:
    breadth:
      - dog food
      - cat food
      - dog treats
      - cat litter
      - toy
    drilldown:
      - dry dog food
      - wet dog food
      - dry cat food
      - cat treats
      - clumping cat litter
      - dog toy
      - pet shampoo
      - flea treatment

  international:
    drilldown:
      - mexican food
      - italian food
      - asian food
      - indian food
      - korean food
      - chinese food
      - japanese food
      - mediterranean food
      - middle eastern food
      - thai food
    
  natural_organic:
    breadth:
      - organic food
      - natural food
    drilldown:
      - organic milk
      - organic eggs
      - organic snacks
      - organic yogurt
      - organic frozen food

  health:
    breadth:
      - vitamins
      - supplements
    drilldown:
      - multivitamins
      - vitamin c
      - vitamin d
      - protein powder
      - probiotics
      - omega 3
      - dumbbells
      - first aid
      - bandages
      - resistance bands
      - yoga mat


  electronics:
    drilldown:
      - headphones
      - earbuds
      - phone charger
      - usb cable
      - power bank


  hardware:
    drilldown:
      - extension cords
      - screws
      - nails
      - duct tape
      - flashlights
      - batteries
      - smart plugs

  office_school_crafts:
    drilldown:
      - printer paper
      - notebooks
      - pens
      - pencils
      - markers
      - glue
      - scissors
      - tape

  party:
    breadth:
      - party supplies
    drilldown:
      - paper plates
      - plastic cutlery
      - balloons
      - napkins
      - birthday candles

    

  kitchen:
    drilldown:
      - water bottle
      - shaker bottle